POST http://foodgramius.ddns.net/api/users/
content-type: application/json

{
    "email": "vpupkin@yandex.ru",
    "username": "vasya.pupkin",
    "first_name": "Вася",
    "last_name": "Пупкин",
    "password": "Qwerty123"
}

###

POST http://localhost/api/auth/token/login/
content-type: application/json

{
    "email": "vpupkin@yandex.ru",
    "password": "Qwerty123"
}

###

GET http://localhost/api/recipes/
content-type: application/json
Authorization: Token b40e4147c346244886039c71b106748a2f9dd3d3

###

GET http://localhost/api/recipes/5
content-type: application/json
Authorization: Token b40e4147c346244886039c71b106748a2f9dd3d3

###

GET http://localhost/api/ingredients/
content-type: application/json
Authorization: Token b40e4147c346244886039c71b106748a2f9dd3d3

###

GET http://localhost/api/ingredients/1/
content-type: application/json
Authorization: Token b40e4147c346244886039c71b106748a2f9dd3d3

###

POST http://localhost/api/recipes/
content-type: application/json
Authorization: Token b40e4147c346244886039c71b106748a2f9dd3d3

{
  "ingredients": [
    {
      "id": 1,
      "quantity": 50
    },
    {
      "id": 2,
      "quantity": 100
    }
  ],
  "tags": [
    1
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "string-1",
  "text": "string-3",
  "cooking_time": 1
}

###
