AMOUNT_MIN_VALUE = 1

COLOR_MAX_LENGHT = 7
COOKING_TIME_MIN_VALUE = 1

FIRSTNAME_MAX_LENGHT = 150

EMAIL_MAX_LENGHT = 254

LASTNAME_MAX_LENGHT = 150

MAX_NUMBER_OF_TAGS_OR_INGREDIENTS_PER_PAGE = 15

NAME_MAX_LENGHT = 50
NUMBER_OF_VISIBLE_CHARACTERS_IN_ADMIN_PANEL = 50

SLUG_MAX_LENGHT = 200

USERNAME_MAX_LENGHT = 150
