# Generated by Django 4.2 on 2024-05-05 08:27

from django.db import migrations, models
import django_extensions.validators
import recipes.color_generator


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default=recipes.color_generator.color_generator, max_length=7, validators=[django_extensions.validators.HexValidator(length=7)], verbose_name='Цвет'),
        ),
    ]
