# Generated by Django 4.2 on 2024-05-05 08:38

from django.db import migrations, models
import recipes.color_generator
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default=recipes.color_generator.color_generator, max_length=7, unique=True, validators=[recipes.validators.isValidHexaCode], verbose_name='Цвет'),
        ),
    ]
