# Generated by Django 3.2.16 on 2024-03-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_api', '0002_auto_20240330_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#ff0000', max_length=16),
        ),
    ]
