# Generated by Django 3.2.16 on 2024-03-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_api', '0005_auto_20240331_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(default=60, verbose_name='Время приготовления в минутах'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='text',
            field=models.TextField(default='', verbose_name='Описание рецепта'),
        ),
    ]
