# Generated by Django 3.2.16 on 2024-03-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_api', '0006_auto_20240331_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(default='', max_length=3600, verbose_name='Описание рецепта'),
        ),
    ]
